# # The topic name is variable 
# x = 5 

# a , b = 10 , 20 
# print(a,b)

#swap the value 
# a , b = b,a 
# print(a,b)

# x = 10
# y= x
# x= 20 
# print(y)

# a = [1, 2, 3]
# b = a
# a.append(4)
# print(b)


#Naming conversion 
# pratik_mishra = 1





#Topic Name: Dynamic Typing
# x = 10
# x = "Pratik"
# x = [10,"pratik"]
# print(x)

# x = 5
# print(type(x))
# x = "5"
# print(type(x))

# x = 10
# y = x
# x = "Hello"
# print(type(y))


# x = "10"
# y = int(x)
# print(type(y))

# x = 5
# print(isinstance(x, int))
# x = "5"
# print(isinstance(x, int))

# x = True
# print(type(x))
# print(isinstance(x, int))

x = 10
print(type(x) == int)
print(isinstance(x, int))




